searchd {
    listen = 127.0.0.1:9312
    listen = 127.0.0.1:9306:mysql
    listen = 0.0.0.0:9308:http
    log = /home/soft/manticoresearch/var/log/manticore/searchd.log
    query_log = /home/soft/manticoresearch/var/log/manticore/query.log
    pid_file = /home/soft/manticoresearch/run/manticore/searchd.pid
    data_dir = /home/soft/manticoresearch/var/lib/manticore
}