# 数据源
source pois_source {
    type = pgsql
	
	# PostgreSQL 连接配置
	sql_host = localhost
	sql_port = 5432
    sql_db = baotou
    sql_user = postgres
    sql_pass = spatialix$168$
	
	sql_query = SELECT mapid, x AS lat, y AS lon, name, telnumber, address, districtid, searchcode, shortname, aliasname, pinyin, poiuid, chainbrand, starlevel FROM public.poi  # 数据源

    sql_attr_uint = mapid
	sql_attr_float = lat
	sql_attr_float = lon
	sql_field_string = name
	sql_attr_string = telnumber
    sql_field_string = address
    sql_attr_uint = districtid
    sql_attr_uint = searchcode
    sql_field_string = shortname
    sql_field_string = aliasname
    sql_attr_string = pinyin
    sql_attr_uint = poiuid
    sql_field_string = chainbrand
    sql_attr_uint = starlevel
}

# 创建索引
index pois_index {
    charset_table = chinese
    morphology = icu_chinese
    stopwords = 'zh'

    type = plain
    source = pois_source
    path = /home/soft/manticoresearch/index/pois
    
    # stopwords = 'zh'
    # rt_field		= name
    # rt_attr_string = name
}

searchd {
    listen = 127.0.0.1:9312
    listen = 127.0.0.1:9306:mysql
    listen = 0.0.0.0:9308:http
    log = /home/soft/manticoresearch/var/log/manticore/searchd.log
    query_log = /home/soft/manticoresearch/var/log/manticore/query.log
    pid_file = /home/soft/manticoresearch/run/manticore/searchd.pid
}
