#line 1 "/home/dev/spatialix/searchservice/out/build/linux-release/thirdparty/manticoresearch/config/flexsphinxql_second.c"

#line 3 "/home/dev/spatialix/searchservice/out/build/linux-release/thirdparty/manticoresearch/config/flexsphinxql_second.c"

#define  YY_INT_ALIGNED long int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define yy5_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer yy5_create_buffer
#endif

#ifdef yy_delete_buffer
#define yy5_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer yy5_delete_buffer
#endif

#ifdef yy_scan_buffer
#define yy5_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer yy5_scan_buffer
#endif

#ifdef yy_scan_string
#define yy5_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string yy5_scan_string
#endif

#ifdef yy_scan_bytes
#define yy5_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes yy5_scan_bytes
#endif

#ifdef yy_init_buffer
#define yy5_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer yy5_init_buffer
#endif

#ifdef yy_flush_buffer
#define yy5_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer yy5_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define yy5_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state yy5_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define yy5_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer yy5_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define yy5push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state yy5push_buffer_state
#endif

#ifdef yypop_buffer_state
#define yy5pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state yy5pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define yy5ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack yy5ensure_buffer_stack
#endif

#ifdef yylex
#define yy5lex_ALREADY_DEFINED
#else
#define yylex yy5lex
#endif

#ifdef yyrestart
#define yy5restart_ALREADY_DEFINED
#else
#define yyrestart yy5restart
#endif

#ifdef yylex_init
#define yy5lex_init_ALREADY_DEFINED
#else
#define yylex_init yy5lex_init
#endif

#ifdef yylex_init_extra
#define yy5lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra yy5lex_init_extra
#endif

#ifdef yylex_destroy
#define yy5lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy yy5lex_destroy
#endif

#ifdef yyget_debug
#define yy5get_debug_ALREADY_DEFINED
#else
#define yyget_debug yy5get_debug
#endif

#ifdef yyset_debug
#define yy5set_debug_ALREADY_DEFINED
#else
#define yyset_debug yy5set_debug
#endif

#ifdef yyget_extra
#define yy5get_extra_ALREADY_DEFINED
#else
#define yyget_extra yy5get_extra
#endif

#ifdef yyset_extra
#define yy5set_extra_ALREADY_DEFINED
#else
#define yyset_extra yy5set_extra
#endif

#ifdef yyget_in
#define yy5get_in_ALREADY_DEFINED
#else
#define yyget_in yy5get_in
#endif

#ifdef yyset_in
#define yy5set_in_ALREADY_DEFINED
#else
#define yyset_in yy5set_in
#endif

#ifdef yyget_out
#define yy5get_out_ALREADY_DEFINED
#else
#define yyget_out yy5get_out
#endif

#ifdef yyset_out
#define yy5set_out_ALREADY_DEFINED
#else
#define yyset_out yy5set_out
#endif

#ifdef yyget_leng
#define yy5get_leng_ALREADY_DEFINED
#else
#define yyget_leng yy5get_leng
#endif

#ifdef yyget_text
#define yy5get_text_ALREADY_DEFINED
#else
#define yyget_text yy5get_text
#endif

#ifdef yyget_lineno
#define yy5get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno yy5get_lineno
#endif

#ifdef yyset_lineno
#define yy5set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno yy5set_lineno
#endif

#ifdef yyget_column
#define yy5get_column_ALREADY_DEFINED
#else
#define yyget_column yy5get_column
#endif

#ifdef yyset_column
#define yy5set_column_ALREADY_DEFINED
#else
#define yyset_column yy5set_column
#endif

#ifdef yywrap
#define yy5wrap_ALREADY_DEFINED
#else
#define yywrap yy5wrap
#endif

#ifdef yyalloc
#define yy5alloc_ALREADY_DEFINED
#else
#define yyalloc yy5alloc
#endif

#ifdef yyrealloc
#define yy5realloc_ALREADY_DEFINED
#else
#define yyrealloc yy5realloc
#endif

#ifdef yyfree
#define yy5free_ALREADY_DEFINED
#else
#define yyfree yy5free
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yy5wrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int32_t yy_accept[297] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   68,   66,
       65,   65,    6,   66,   66,   60,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   66,    3,    5,   67,    7,
       67,    8,   10,   13,   67,   12,   65,    0,   59,    9,
        1,   59,   60,   61,    0,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   35,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   51,   61,   61,   61,   61,    0,    0,
        3,    4,    2,    7,   10,   11,    0,   59,   64,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   34,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   47,   61,
       61,   61,   61,   61,   61,   61,   61,   61,    0,    0,
       62,    0,   59,   64,   61,   61,   61,   61,   61,   61,
       61,   21,   61,   61,   24,   61,   61,   61,   61,   30,
       61,   32,   33,   61,   61,   61,   61,   40,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   56,   57,    0,   63,   61,   61,   16,   61,   61,
       61,   61,   22,   61,   61,   61,   27,   61,   31,   61,

       61,   38,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   49,   61,   61,   61,   61,   14,   61,   61,   61,
       61,   20,   23,   25,   61,   61,   61,   36,   61,   61,
       61,   42,   61,   61,   61,   61,   48,   61,   50,   61,
       61,   61,   61,   61,   17,   61,   61,   61,   28,   61,
       37,   61,   61,   61,   44,   61,   46,   58,   61,   61,
       61,   61,   61,   61,   19,   61,   61,   39,   61,   61,
       61,   61,   53,   61,   55,   61,   18,   26,   29,   61,
       61,   61,   61,   61,   15,   61,   43,   61,   61,   61,
       41,   61,   52,   54,   45,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    1,
        1,    5,    6,    1,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    1,    1,    1,
        1,    1,    1,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
        1,   38,    1,    1,   21,   39,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   21,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    1,    5,
        6,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    8,    9,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7
    } ;

static const flex_int32_t yy_base[312] =
    {   0,
        0,    0,   62,   63,   66,   68,   70,   72,  875,  887,
       74,   76,  887,   78,  858,   74,  845,   63,  842,   74,
       76,   72,   79,   87,   82,  105,  115,  119,   92,  122,
      107,  134,  146,  137,  165,  838,    0,  887,  838,    0,
      887,  887,    0,  887,    0,  887,  153,  164,  164,  887,
      887,  172,   81,  820,    0,  138,  179,  168,  180,  172,
      181,  183,  203,  198,  187,  195,  200,  207,  190,  214,
      221,  224,  818,  217,  201,  229,  235,  254,  232,  253,
      247,  244,  265,  782,  280,  276,  250,  274,  782,  751,
        0,  887,  887,    0,    0,  887,  307,  279,    0,  304,

      260,  289,  311,  286,  313,  315,  320,  317,  314,  318,
      326,  336,  340,  337,  341,  339,  777,  323,  343,  345,
      364,  362,  368,  369,  371,  372,  380,  373,  776,  387,
      377,  381,  382,  391,  399,  400,  401,  398,  746,  745,
      887,  772,  771,    0,  409,  422,  402,  408,  427,  415,
      426,  769,  429,  425,  768,  438,  430,  442,  452,  765,
      449,  764,  763,  443,  447,  450,  454,  762,  463,  468,
      479,  482,  491,  474,  476,  494,  495,  487,  498,  496,
      505,  761,  760,  731,  887,  507,  517,  756,  513,  503,
      521,  525,  754,  532,  512,  534,  539,  522,  741,  541,

      545,  734,  531,  556,  549,  540,  561,  564,  568,  573,
      557,  574,  584,  588,  567,  591,  732,  571,  577,  598,
      602,  713,  702,  649,  599,  604,  600,  647,  608,  601,
      616,  643,  628,  611,  631,  630,  605,   88,  575,  633,
      614,  632,  626,  638,  548,  651,  646,  655,  472,  659,
      470,  666,  663,  673,  457,  667,  403,  887,  676,  678,
      680,  681,  682,  690,  355,  672,  695,  347,  689,  705,
      706,  712,  292,  699,  277,  697,  251,  243,  238,  708,
      724,  728,  725,  733,  226,  742,  209,  739,  731,  748,
      173,  750,  150,  141,  132,  887,  794,  803,  812,  817,

      820,  827,  836,  845,  854,  861,  130,  866,  869,  874,
      877
    } ;

static const flex_int32_t yy_def[312] =
    {   0,
      296,    1,  297,  297,  298,  298,  299,  299,  296,  296,
      296,  296,  296,  296,  296,  296,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  301,  302,  296,  303,  304,
      296,  296,  305,  296,  306,  296,  296,  296,  296,  296,
      296,  296,  296,  300,  307,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  308,  309,
      302,  296,  296,  304,  305,  296,  296,  296,  310,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  311,  309,
      296,  296,  296,  310,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  311,  296,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,

      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  296,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  300,  300,  300,
      300,  300,  300,  300,  300,    0,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

static const flex_int32_t yy_nxt[952] =
    {   0,
       10,   11,   12,   13,   10,   10,   10,   14,   15,   16,
       17,   18,   19,   20,   21,   19,   22,   23,   24,   25,
       19,   26,   27,   19,   19,   28,   29,   30,   31,   32,
       33,   34,   19,   35,   19,   19,   19,   10,   36,   18,
       19,   20,   21,   19,   22,   23,   24,   25,   26,   27,
       19,   19,   28,   29,   30,   31,   32,   33,   34,   19,
       35,   19,   19,   19,   38,   38,   39,   39,   41,   42,
       41,   42,   44,  296,   44,   47,   47,   47,   47,   48,
       48,   52,  296,   53,  296,   57,  296,   49,   52,  296,
       53,   60,  296,   56,   62,  258,   58,  296,  296,   59,

       63,   64,  296,   41,   61,   41,   66,   45,   46,   45,
       46,   67,   65,   57,   75,  296,   50,  296,   77,   60,
       56,   62,   78,   58,   68,  296,   59,   63,   64,  296,
       69,   61,  296,   66,   70,   72,   99,   79,   67,   65,
       71,   75,  296,   73,  296,   74,   77,  296,  296,   80,
       78,  296,   68,   76,   47,   47,  296,   83,   69,   81,
      296,   86,   70,   72,   79,   48,   48,   71,  100,   82,
       73,   84,   74,   49,   85,  296,   87,   80,  296,   97,
       76,   98,  296,  296,   88,   83,   81,   97,   86,  296,
      296,  296,  101,  296,  104,  100,   82,  296,   84,  102,

      296,   85,   50,  103,   87,  296,  105,   97,  296,  111,
      296,  296,   88,  296,  106,   97,  110,  296,  107,  296,
      101,  104,  114,  109,  296,  112,  102,  296,  108,  113,
      103,  296,  119,  105,  296,  115,  296,  111,  116,  296,
      117,  106,  296,  110,  120,  296,  107,  118,  296,  114,
      109,  126,  112,  296,  296,  108,  113,  296,  121,  119,
      296,  296,  115,  296,  296,  122,  116,  123,  117,  137,
      296,  130,  120,  131,  118,  296,  124,  132,  147,  126,
      125,  127,  128,  129,  296,  121,  296,  296,   98,  135,
      296,  133,  136,  122,   97,  123,  296,  137,  130,  296,

      131,  151,  296,  124,  138,  132,  147,  125,  127,  128,
      129,  134,  142,  142,  296,  145,  143,  135,  148,  133,
      136,  296,   97,  296,  296,  296,  156,  296,  296,  151,
      296,  138,  146,  296,  149,  154,  296,  150,  134,  152,
      155,  158,  164,  145,  153,  148,  296,  296,  157,  296,
      296,  296,  161,  296,  156,  296,  162,  296,  159,  146,
      165,  149,  160,  154,  150,  296,  152,  155,  163,  158,
      164,  153,  296,  166,  296,  157,  168,  167,  296,  296,
      161,  296,  296,  296,  162,  159,  171,  296,  165,  160,
      296,  296,  296,  169,  170,  163,  172,  296,  175,  173,

      166,  296,  174,  177,  168,  167,  178,  176,  296,  296,
      296,  296,  296,  296,  171,  179,  183,  188,  296,  296,
      169,  170,  186,  172,  180,  296,  175,  173,  181,  174,
      177,  182,  296,  178,  176,  296,  296,  296,  189,  296,
      296,  187,  179,  191,  183,  188,  190,  193,  296,  195,
      186,  180,  296,  296,  196,  181,  192,  296,  182,  296,
      296,  194,  296,  198,  296,  189,  201,  296,  200,  187,
      191,  199,  203,  296,  190,  193,  197,  195,  296,  205,
      296,  196,  296,  192,  296,  202,  296,  204,  194,  296,
      206,  198,  296,  209,  201,  200,  207,  296,  199,  210,

      203,  296,  208,  197,  296,  296,  296,  205,  296,  211,
      212,  214,  202,  296,  204,  296,  213,  296,  206,  215,
      216,  209,  296,  296,  207,  217,  210,  296,  219,  218,
      208,  296,  296,  220,  224,  296,  221,  211,  212,  214,
      222,  296,  296,  213,  296,  225,  215,  223,  216,  296,
      296,  296,  227,  217,  226,  296,  219,  218,  296,  296,
      220,  224,  230,  232,  221,  228,  296,  296,  222,  229,
      233,  296,  231,  225,  296,  223,  234,  296,  296,  227,
      238,  296,  226,  296,  296,  296,  235,  296,  237,  230,
      242,  232,  228,  236,  296,  240,  229,  233,  296,  241,

      231,  296,  244,  239,  234,  245,  243,  238,  296,  296,
      296,  296,  296,  235,  296,  296,  237,  242,  296,  250,
      236,  296,  248,  240,  296,  252,  296,  241,  246,  244,
      239,  247,  245,  249,  243,  253,  296,  251,  296,  254,
      296,  296,  296,  296,  260,  255,  259,  250,  296,  248,
      256,  261,  252,  296,  257,  246,  296,  296,  247,  296,
      249,  296,  262,  253,  251,  296,  264,  254,  263,  296,
      266,  260,  255,  296,  259,  265,  296,  296,  256,  261,
      269,  257,  296,  296,  267,  270,  296,  268,  296,  262,
      296,  296,  296,  273,  264,  263,  275,  276,  266,  296,

      296,  278,  265,  271,  277,  296,  272,  296,  269,  296,
      274,  267,  296,  270,  268,  296,  296,  282,  296,  279,
      280,  273,  296,  296,  275,  276,  285,  281,  278,  284,
      271,  283,  277,  272,  296,  296,  286,  274,  296,  287,
      288,  296,  296,  296,  296,  282,  279,  280,  290,  296,
      289,  296,  296,  285,  281,  293,  284,  291,  296,  283,
      296,  292,  294,  286,  296,  295,  296,  287,  288,  185,
      296,  296,  296,  296,  296,  296,  290,  289,  296,  296,
      143,  143,  293,  141,  185,  291,  296,  296,  292,  141,
      294,   89,  296,  295,   37,   37,   37,   37,   37,   37,

       37,   37,   37,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   43,   43,   43,   43,   43,   43,   43,   43,
       43,   54,   54,   54,   90,   90,   90,   91,  296,   91,
      296,   91,   91,   91,   91,   91,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   94,   93,   89,   94,   94,
       94,   94,  296,   94,   95,   55,   95,   95,   95,   95,
       95,   96,   51,   96,   96,   96,   96,   96,   96,   96,
      139,  139,  139,  140,  296,  140,  296,  140,  144,  296,
      144,  184,  296,  184,  296,  184,    9,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

static const flex_int32_t yy_chk[952] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    3,    4,    5,    5,
        6,    6,    7,   18,    8,   11,   11,   12,   12,   14,
       14,   16,   22,   16,   20,   20,   21,   14,   53,   23,
       53,   21,   25,   18,   22,  238,   20,   24,  238,   20,

       22,   23,   29,    5,   21,    6,   25,    7,    7,    8,
        8,   25,   24,   20,   29,   26,   14,   31,   31,   21,
       18,   22,   31,   20,   26,   27,   20,   22,   23,   28,
       27,   21,   30,   25,   27,   28,  307,   31,   25,   24,
       27,   29,  295,   28,   32,   28,   31,   34,   56,   32,
       31,  294,   26,   30,   47,   47,   33,   33,   27,   32,
      293,   34,   27,   28,   31,   48,   48,   27,   56,   32,
       28,   33,   28,   49,   33,   35,   35,   32,   58,   49,
       30,   52,   60,  291,   35,   33,   32,   52,   34,   57,
       59,   61,   57,   62,   60,   56,   32,   65,   33,   58,

       69,   33,   48,   59,   35,   66,   61,   49,   64,   66,
       67,   75,   35,   63,   62,   52,   65,   68,   63,  287,
       57,   60,   69,   64,   70,   67,   58,   74,   63,   68,
       59,   71,   75,   61,   72,   70,  285,   66,   71,   76,
       72,   62,   79,   65,   76,   77,   63,   74,  279,   69,
       64,   79,   67,  278,   82,   63,   68,   81,   77,   75,
       87,  277,   70,   80,   78,   78,   71,   78,   72,   87,
      101,   81,   76,   82,   74,   83,   78,   83,  101,   79,
       78,   80,   80,   80,   88,   77,   86,  275,   98,   86,
       85,   85,   86,   78,   98,   78,  104,   87,   81,  102,

       82,  104,  273,   78,   88,   83,  101,   78,   80,   80,
       80,   85,   97,   97,  100,  100,   97,   86,  102,   85,
       86,  103,   98,  105,  109,  106,  109,  108,  110,  104,
      107,   88,  100,  118,  103,  107,  111,  103,   85,  105,
      108,  111,  118,  100,  106,  102,  112,  114,  110,  116,
      113,  115,  114,  119,  109,  120,  115,  268,  112,  100,
      119,  103,  113,  107,  103,  265,  105,  108,  116,  111,
      118,  106,  122,  120,  121,  110,  122,  121,  123,  124,
      114,  125,  126,  128,  115,  112,  125,  131,  119,  113,
      127,  132,  133,  123,  124,  116,  126,  130,  130,  127,

      120,  134,  128,  132,  122,  121,  133,  131,  138,  135,
      136,  137,  147,  257,  125,  134,  138,  147,  148,  145,
      123,  124,  145,  126,  135,  150,  130,  127,  136,  128,
      132,  137,  146,  133,  131,  154,  151,  149,  148,  153,
      157,  146,  134,  150,  138,  147,  149,  153,  156,  156,
      145,  135,  158,  164,  157,  136,  151,  165,  137,  161,
      166,  154,  159,  159,  167,  148,  165,  255,  164,  146,
      150,  161,  167,  169,  149,  153,  158,  156,  170,  170,
      251,  157,  249,  151,  174,  166,  175,  169,  154,  171,
      171,  159,  172,  174,  165,  164,  172,  178,  161,  175,

      167,  173,  173,  158,  176,  177,  180,  170,  179,  176,
      177,  179,  166,  190,  169,  181,  178,  186,  171,  180,
      181,  174,  195,  189,  172,  186,  175,  187,  189,  187,
      173,  191,  198,  190,  195,  192,  191,  176,  177,  179,
      192,  203,  194,  178,  196,  196,  180,  194,  181,  197,
      206,  200,  198,  186,  197,  201,  189,  187,  245,  205,
      190,  195,  203,  205,  191,  200,  204,  211,  192,  201,
      206,  207,  204,  196,  208,  194,  207,  215,  209,  198,
      211,  218,  197,  210,  212,  239,  208,  219,  210,  203,
      215,  205,  200,  209,  213,  213,  201,  206,  214,  214,

      204,  216,  218,  212,  207,  219,  216,  211,  220,  225,
      227,  230,  221,  208,  226,  237,  210,  215,  229,  227,
      209,  234,  225,  213,  241,  230,  231,  214,  220,  218,
      212,  221,  219,  226,  216,  231,  243,  229,  233,  233,
      236,  235,  242,  240,  241,  234,  240,  227,  244,  225,
      235,  242,  230,  232,  236,  220,  247,  228,  221,  224,
      226,  246,  243,  231,  229,  248,  246,  233,  244,  250,
      248,  241,  234,  253,  240,  247,  252,  256,  235,  242,
      253,  236,  266,  254,  250,  254,  259,  252,  260,  243,
      261,  262,  263,  260,  246,  244,  262,  263,  248,  269,

      264,  266,  247,  256,  264,  267,  259,  276,  253,  274,
      261,  250,  223,  254,  252,  270,  271,  271,  280,  267,
      269,  260,  272,  222,  262,  263,  276,  270,  266,  274,
      256,  272,  264,  259,  281,  283,  280,  261,  282,  281,
      282,  289,  217,  284,  202,  271,  267,  269,  284,  288,
      283,  199,  286,  276,  270,  289,  274,  286,  290,  272,
      292,  288,  290,  280,  193,  292,  188,  281,  282,  184,
      183,  182,  168,  163,  162,  160,  284,  283,  155,  152,
      143,  142,  289,  140,  139,  286,  129,  117,  288,   90,
      290,   89,   84,  292,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  299,  299,  299,  299,  299,  299,  299,  299,
      299,  300,  300,  300,  301,  301,  301,  302,   73,  302,
       54,  302,  302,  302,  302,  302,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  304,   39,   36,  304,  304,
      304,  304,   19,  304,  305,   17,  305,  305,  305,  305,
      305,  306,   15,  306,  306,  306,  306,  306,  306,  306,
      308,  308,  308,  309,    9,  309,    0,  309,  310,    0,
      310,  311,    0,  311,    0,  311,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,

      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      296
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
#line 2 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"

#if _WIN32
#define YY_NO_UNISTD_H 1
#endif

#include "bissphinxql_second.h"

#define YY_NO_INPUT

#ifdef __GNUC__
	#pragma GCC diagnostic push
	#pragma GCC diagnostic ignored "-Wsign-compare"
	#pragma GCC diagnostic ignored "-Wpragmas"
	#pragma GCC diagnostic ignored "-Wunneeded-internal-declaration"
#endif

#if _WIN32
#pragma warning(push,1)
#endif

#define STORE_BOUNDS \
	{ \
		lvalp->m_iStart = yytext - pParser->m_pBuf; \
		lvalp->m_iEnd = lvalp->m_iStart + yyleng; \
		pParser->m_pLastTokenStart = yytext; \
	}

#define Q_START \
	{ \
		pParser->m_pLastTokenStart = yytext  + yyleng - 1; \
	    lvalp->m_iStart = yytext  + yyleng - pParser->m_pBuf - 1; \
	}

#define Q_END \
	{ \
		lvalp->m_iEnd = yytext + yyleng - pParser->m_pBuf; \
	}

#line 984 "/home/dev/spatialix/searchservice/out/build/linux-release/thirdparty/manticoresearch/config/flexsphinxql_second.c"

#line 986 "/home/dev/spatialix/searchservice/out/build/linux-release/thirdparty/manticoresearch/config/flexsphinxql_second.c"

#define INITIAL 0
#define ccomment 1
#define QSTR 2
#define BACKTICK 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 64 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"


#line 1250 "/home/dev/spatialix/searchservice/out/build/linux-release/thirdparty/manticoresearch/config/flexsphinxql_second.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 297 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 296 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 66 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ BEGIN(ccomment); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 67 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 68 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"

	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 69 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"

	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 70 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 72 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ Q_START; BEGIN (QSTR); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 73 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 74 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{  Q_END; BEGIN(INITIAL); return TOK_QUOTED_STRING; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 76 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ Q_START; BEGIN (BACKTICK); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 77 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
/* eat everything except \n, \, ` */
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 78 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
/* eat one symbol after \ (aka escaping) except \n  */
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 79 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{
							Q_END;
							BEGIN(INITIAL);
							return TOK_BACKTICKED_SUBKEY;
						}
	YY_BREAK
case 13:
/* rule 13 can match eol */
#line 86 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
YY_RULE_SETUP
case YY_STATE_EOF(BACKTICK):
#line 86 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{
							BEGIN(INITIAL);
							return -1;
						}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 91 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_ATTACH; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_ATTRIBUTES; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 93 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_CACHE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 94 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_CLUSTER; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 95 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_COMMITTED; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 96 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_COMPRESS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 97 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_DELETE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_DROP; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_FLUSH; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 100 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_FREEZE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 101 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_FROM; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 102 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_GLOBAL; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 103 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_HOSTNAMES; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_INDEX; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 105 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_INDEXES; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 106 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_ISOLATION; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 107 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_KILL; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 108 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_LEVEL; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 109 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_LIKE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 110 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_LOGS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 111 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_OFF; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 112 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_ON; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 113 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_OPTION; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 114 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_PLUGINS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_QUERY; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 116 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_RAMCHUNK; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 117 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_READ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 118 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_RECONFIGURE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 119 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_RELOAD; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 120 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_REPEATABLE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_RTINDEX; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_SERIALIZABLE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_SESSION; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_SET; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_SONAME; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_TABLE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_TABLES; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_TO; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_TRANSACTION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_TRUNCATE; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_UNCOMMITTED; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 132 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_UNFREEZE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 133 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_WAIT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 134 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_WITH; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_SYSTEM_DOT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 139 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; lvalp->m_fValue = (float)strtod ( yytext, NULL ); return TOK_CONST_FLOAT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 140 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; lvalp->SetValueInt ( strtoull ( yytext, NULL, 10 ), false); return TOK_CONST_INT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 142 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_IDENT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 143 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; ++lvalp->m_iStart; --lvalp->m_iEnd; return TOK_IDENT; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 144 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; ++lvalp->m_iStart; --lvalp->m_iEnd; return TOK_IDENT; } // allow `123xyz` column names
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 145 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{ STORE_BOUNDS; return TOK_SYSVAR; }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 147 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"

	YY_BREAK
case 66:
YY_RULE_SETUP
#line 148 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
{  return yytext[0]; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 150 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"
ECHO;
	YY_BREAK
#line 1652 "/home/dev/spatialix/searchservice/out/build/linux-release/thirdparty/manticoresearch/config/flexsphinxql_second.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ccomment):
case YY_STATE_EOF(QSTR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 297 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 297 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 296);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 150 "/home/dev/spatialix/searchservice/thirdparty/manticoresearch/src/sphinxql_second.l"


static void yy5lex_unhold ( yyscan_t yyscanner )
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( YY_CURRENT_BUFFER )
	{
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
	}
}

#if _WIN32
#pragma warning(pop)
#endif

#ifdef __GNUC__
	#pragma GCC diagnostic pop
#endif
