# Archived bison/flex products, so that a regular (offline) build needs neither bison nor flex.
#
# The generated parsers/lexers are consumed as *text includes* - sphinxjson.cpp does
# `#include "bissphinxjson.c"` / `#include "flexsphinxjson.c"` - so CMake's only job is to make
# those files appear on the include path (${MANTICORE_BINARY_DIR}/config, exposed by the
# generated_config target). Once the files exist, bison/flex and their CMake modules have no reason
# to be involved at all. One generation serves every platform: each consumer defines YY_NO_UNISTD_H
# before including, the multiple lexers are kept apart by the `%option prefix=` written in the .l
# files, and `%option noyywrap` + reentrant makes the output self-contained (no libfl).
#
# Two states, switched by MANTICORE_REGEN_GRAMMAR:
#
#   OFF (default, this is what offline build machines use)
#       find_package(BISON/FLEX) is never called. The 23 archived products must be present in
#       src/generated_grammar/, and the hashes of every .y/.l must match grammar_sources.sha256.
#       Any deviation is a FATAL_ERROR - never a silent fallback to stale products.
#
#   ON (turned on by hand, on a machine that has bison 3.8.2 + flex 2.6.4)
#       Products are generated by the upstream logic and written back into src/generated_grammar/
#       together with a refreshed hash manifest at the end of the build, so that "generate" and
#       "update the archive" are one and the same operation.
#
# Turn it ON only when the pinned Manticore version changes or a .y/.l is edited; the hash check
# below refuses to build if that happened without regeneration.

if (__grammar_archive_included)
	return ()
endif ()
set ( __grammar_archive_included YES )

include ( printers )

option ( MANTICORE_REGEN_GRAMMAR "regenerate bison/flex products and refresh src/generated_grammar (needs bison 3.8.2 + flex 2.6.4)" OFF )

set ( MANTICORE_GRAMMAR_DIR "${MANTICORE_SOURCE_DIR}/src/generated_grammar" CACHE PATH "Folder with archived bison/flex products" )
set ( MANTICORE_GRAMMAR_MANIFEST "grammar_sources.sha256" )

# must stay in sync with the MY_BISON / MY_FLEX calls in src/CMakeLists.txt
set ( MANTICORE_BISON_GRAMMARS sphinxexpr sphinxselect sphinxjson sphinxql ddl sphinxql_debug sphinxql_second sphinxql_extra )
set ( MANTICORE_FLEX_LEXERS sphinxjson sphinxexpr sphinxql ddl sphinxql_debug sphinxql_second sphinxql_extra )

# names of the archived products (bis<name>.c/.h for grammars, flex<name>.c for lexers)
function ( grammar_product_names OUTVAR )
	set ( _names "" )
	foreach (_g ${MANTICORE_BISON_GRAMMARS})
		list ( APPEND _names "bis${_g}.c" "bis${_g}.h" )
	endforeach ()
	foreach (_l ${MANTICORE_FLEX_LEXERS})
		list ( APPEND _names "flex${_l}.c" )
	endforeach ()
	set ( ${OUTVAR} "${_names}" PARENT_SCOPE )
endfunction ()

# names of the grammar sources the manifest covers
function ( grammar_source_names OUTVAR )
	set ( _names "" )
	foreach (_g ${MANTICORE_BISON_GRAMMARS})
		list ( APPEND _names "${_g}.y" )
	endforeach ()
	foreach (_l ${MANTICORE_FLEX_LEXERS})
		list ( APPEND _names "${_l}.l" )
	endforeach ()
	set ( ${OUTVAR} "${_names}" PARENT_SCOPE )
endfunction ()

set ( _REGEN_HINT "Configure once on a machine with bison 3.8.2 + flex 2.6.4 as:\n    cmake -DMANTICORE_REGEN_GRAMMAR=ON ... && cmake --build ...\nThe build writes the products and the refreshed manifest back into ${MANTICORE_GRAMMAR_DIR}; commit them together with the sources." )

# OFF state: verify the archive against the current .y/.l and put the products where the
# consuming .cpp files expect to include them from.
function ( stage_archived_grammar SRC_DIR OUT_DIR )
	grammar_product_names ( _products )

	set ( _missing "" )
	foreach (_f ${_products})
		if (NOT EXISTS "${MANTICORE_GRAMMAR_DIR}/${_f}")
			list ( APPEND _missing "${_f}" )
		endif ()
	endforeach ()
	if (_missing)
		string ( REPLACE ";" " " _missing_str "${_missing}" )
		message ( FATAL_ERROR
				"Archived bison/flex products are missing in ${MANTICORE_GRAMMAR_DIR}:\n    ${_missing_str}\n"
				"${_REGEN_HINT}" )
	endif ()

	set ( _manifest "${MANTICORE_GRAMMAR_DIR}/${MANTICORE_GRAMMAR_MANIFEST}" )
	if (NOT EXISTS "${_manifest}")
		message ( FATAL_ERROR "Grammar hash manifest is missing: ${_manifest}\n${_REGEN_HINT}" )
	endif ()

	# manifest lines are '<sha256> <filename>'
	file ( STRINGS "${_manifest}" _lines )
	set ( _stale "" )
	grammar_source_names ( _sources )
	foreach (_src ${_sources})
		if (NOT EXISTS "${SRC_DIR}/${_src}")
			message ( FATAL_ERROR "Grammar source ${SRC_DIR}/${_src} not found, but it is listed in the build" )
		endif ()
		file ( SHA256 "${SRC_DIR}/${_src}" _hash )

		set ( _recorded "" )
		foreach (_line ${_lines})
			if (_line MATCHES "^([0-9a-fA-F]+)[ \t]+(.+)$")
				if (CMAKE_MATCH_2 STREQUAL _src)
					set ( _recorded "${CMAKE_MATCH_1}" )
					break ()
				endif ()
			endif ()
		endforeach ()

		if (NOT _recorded)
			list ( APPEND _stale "${_src} (not in manifest)" )
		elseif (NOT _recorded STREQUAL _hash)
			list ( APPEND _stale "${_src} (changed)" )
		endif ()
	endforeach ()

	if (_stale)
		string ( REPLACE ";" "\n    " _stale_str "${_stale}" )
		message ( FATAL_ERROR
				"Grammar sources no longer match the archived products:\n    ${_stale_str}\n"
				"${_REGEN_HINT}" )
	endif ()

	# configure_file also makes cmake re-run when an archived product changes
	foreach (_f ${_products})
		configure_file ( "${MANTICORE_GRAMMAR_DIR}/${_f}" "${OUT_DIR}/${_f}" COPYONLY )
	endforeach ()

	infomsg ( "Using archived bison/flex products from ${MANTICORE_GRAMMAR_DIR} (bison/flex not needed)" )
endfunction ()

# ON state: write the freshly generated products and the refreshed manifest back into the archive,
# as a post-build step of TRG (by then every product has been generated).
function ( add_grammar_writeback TRG SRC_DIR OUT_DIR )
	if (NOT MANTICORE_REGEN_GRAMMAR)
		return ()
	endif ()

	string ( REPLACE ";" "," _bisons "${MANTICORE_BISON_GRAMMARS}" )
	string ( REPLACE ";" "," _flexes "${MANTICORE_FLEX_LEXERS}" )

	add_custom_command ( TARGET ${TRG} POST_BUILD
			COMMAND "${CMAKE_COMMAND}"
			"-DSRC_DIR=${SRC_DIR}"
			"-DBIN_CONFIG=${OUT_DIR}"
			"-DGRAMMAR_DIR=${MANTICORE_GRAMMAR_DIR}"
			"-DMANIFEST_NAME=${MANTICORE_GRAMMAR_MANIFEST}"
			"-DBISON_LIST=${_bisons}"
			"-DFLEX_LIST=${_flexes}"
			-P "${MANTICORE_SOURCE_DIR}/cmake/grammar_writeback.cmake"
			COMMENT "Writing bison/flex products back to ${MANTICORE_GRAMMAR_DIR}"
			VERBATIM )
endfunction ()
